language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_073fef5015cf_key -iv $encrypted_073fef5015cf_iv
  -in application.properties.enc -out ~\/big-ws/src/main/resources/application.properties
  -d
