language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_37c734d3f559_key -iv $encrypted_37c734d3f559_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
env:
	secure: OADisgIdKmWNGyV4bn1TplLwL3+/sc5R/GMvKP3InGr4/F8ZrA6qFufor+eJkQHWTzATa5q5ABpw4TOxwRxlddNH6uM0V4rBoaNEEhCCmdtDqn0ff1PpPMTFRLyfJF7v5jbdq65le0+G3ULjQz7a/cErbXf0nMHwxUz+dSr5h70rvBjckTaccClTOWeS0fpJGWYlsBGJpjHWvIentbtiSTGHDp8goL8dMlPFcjHgTRjc7q7/Fjanehm/DZLISyDTnUKJWVtb9TF2nHlBfmbIFftKD9/6EO5I8ZOdruiqqh9X8d5dK2/4n1Bj3IM0zODXH/JfwX5Hp3XgBNFENpXJZIv/WCXc+blKoQcPitBK76yOsk8BgDrrjDOh0BzHdXvQjQDCQ5B3Kui8iTEJdLzc5CvsXfhNq/6Vrvad/hxyqalsYjaZPczMeN/Ub1D/bYK9Wdw+6mdmuvzxkfzpA7hQOxnbCGuxoxZo8BepVg6ec5xcoMHc/Vp8TXSyE3dcTkyr8/PGhFH7yxHfB3e2RKuikoGFxynY+wpT/niPzH5T1uDCXGcVmKsSx7gIC4kimjiOAwvcqdIsHIrC2PYOFcXnpPeqvfokDZdwhDBeSa9Yh7e8kr2pYfFmrsdNUA/AENOTf8hKbXJdV9dTDPKAU5QWne8/sfeWVPNaDwHo/sPl/gk=