language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_37c734d3f559_key -iv $encrypted_37c734d3f559_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
env:
  global:
    secure: Zas98SO7stQ+Hf8YIJ33Wd0N34YbX4cyw9SRefghFe4wxQOzDDNu+HylG4B85uDycxch1kCosD1oTARqJAd6M3lkW9gFSCRxJQErwspTHuL/xCzZta+qyWlQdw281Id1tcGDjTiTXDmFhsHwJ0jczUpqjsLYQgd0UD0ZP4GW4XxcnTWV6hcn++yj+Y2pTpKlKuE8VLc8A8LReSFgVXX24mW0Ezqk9c/IplCM86ridzpTb7pfeW0dB5bC2/aw4rXMLKdyB7UFq5aXRxbYDJ/prGGxDOk8JKhIqYKveQcNd7VLeHt1Nfzg5vdiZATO7C/QnVD+cCEMkyhm/AvIpFMv/FhyhH4IjQpgsstbL+np4iuyDY8AkLltAH7AfhVXWGEM82WgLNtc1geQkWY8rg473p9rvfoT7H54/N8Ojc0V6ss4I8HdOkBLPa2LN01cbUk1zV4fiiUg372dn9jcGqx9FO48452cSClAoo5/0cdDTidWxvt+FV8RzxvnuQPwtBcB1oRefI7c1qCP7sqxrdaS0zBCE2hiIZOTWFclKveov1AP8awqO1RFMwRpwf3RQhWshNIXZonPrhV/B0NOpcBQu2aiw3OzPY/aCJQU9WIeTTf+NDcQ57BRT5tFAgyYXOtMG/7GWedFs74xlFvJzPljgnWJ31XzYi9NbUnZ+y6Sfk0=
